# Generated by Django 4.2.16 on 2024-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=100)),
                ('current_price', models.IntegerField(null=True)),
                ('price_change', models.IntegerField(null=True)),
                ('price_change_rate', models.FloatField(null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('trading_value', models.BigIntegerField(null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('issued_shares', models.BigIntegerField(null=True)),
                ('week_change_rate', models.FloatField(null=True)),
                ('month_change_rate', models.FloatField(null=True)),
                ('year_change_rate', models.FloatField(null=True)),
                ('three_year_change_rate', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('debt_ratio', models.FloatField(null=True)),
                ('retention_ratio', models.FloatField(null=True)),
                ('revenue_growth_rate', models.FloatField(null=True)),
                ('eps_growth_rate', models.CharField(max_length=20, null=True)),
                ('roa', models.FloatField(null=True)),
                ('roe', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('bps', models.FloatField(null=True)),
                ('per', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('ev_ebitda', models.FloatField(null=True)),
                ('revenue', models.CharField(max_length=100, null=True)),
                ('evebitda', models.FloatField(null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('sector_per', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
