# Generated by Django 4.2.16 on 2024-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='reserve_ratio',
        ),
        migrations.AddField(
            model_name='stock',
            name='evebitda',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='retention_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='eps_growth_rate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='revenue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
