# Generated by Django 4.2.16 on 2024-11-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_description_userprofile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resolution',
            field=models.TextField(blank=True, default='주식 투자로 부자되기'),
        ),
    ]
