# Generated by Django 4.2.16 on 2024-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentStyle',
            fields=[
                ('style_id', models.IntegerField(choices=[(1, '안정형 투자자'), (2, '위험중립형 투자자'), (3, '공격투자형 투자자')], primary_key=True, serialize=False, verbose_name='투자 성향 스타일')),
            ],
        ),
    ]
