# Generated by Django 4.2.16 on 2024-11-22 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentStyle',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('investment_style', models.IntegerField(choices=[(1, '안정형 투자자'), (2, '위험중립형 투자자'), (3, '공격투자형 투자자')], help_text='1: 안정형 투자자, 2: 위험중립형 투자자, 3: 공격투자형 투자자')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_style', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment_style',
            },
        ),
    ]
