# Generated by Django 4.2.16 on 2024-11-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_style', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentstyle',
            old_name='investment_style',
            new_name='style_name',
        ),
        migrations.RemoveField(
            model_name='investmentstyle',
            name='user',
        ),
    ]
