# Generated by Django 4.2.16 on 2024-11-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_style', '0002_stylequestion_stylechoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentstyle',
            name='name',
            field=models.CharField(default='Default Style', max_length=100, verbose_name='투자 성향 이름'),
        ),
    ]
